# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Dinali Jay
title: Project Manager
email: dinalijay@gmail.com
# email_title: Email (Email title override)
# phone: +61 44 99 66 446
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: dinalijay
linkedin_username: dinalijay
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  I am a highly skilled and results-driven Project Manager with 5+ years of experience in leading and delivering successful IT projects. I have a strong background in gathering and analyzing data, developing technical solutions, and communicating with stakeholders. I am proficient in a variety of technical tools and technologies, including SQL, Python, and Tableau. I am an experienced problem-solver with a proven track record of delivering projects on time and within budget. I have a proven track record of driving project development from concept to launch and exceeding goals for success. I have a strong technical background in software development and agile methodologies, and am well-versed in project management best practices.


#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Cartesi
        sub_title: Technical Community Development Manager 
        caption: Remote | Oct 2021 - Dec 2022
        link: cartesi.io
        quote: >
          Blockchain Technology
        description: | # this will include new lines to allow paragraphs
          <br>• Successfully led the launch of multiple gaming decentralized applications, driving product development and market expansion resulting in community growth by over 25% within 3 weeks.
          <br>• Collaborated closely with cross-functional teams to drive product development, meeting project milestones and delivering exceptional customer experiences.
          <br>• Conducted market research, analyzed customer data, and used insights to inform strategic product decisions.
          <br>• Expertly managed budgets, resources, and project timelines for the product development team.
          <br>•  Built and nurtured relationships with stakeholders, technical communities, and other key partners to drive community growth and engagement.
          <br>• Proactively identified and addressed community needs, fostering a strong and active developer community that grew by 40%.
          <br>• Acted as a liaison between the core development team and the wider community, ensuring clear communication and alignment on project goals and priorities.
          <br>• Led a community of 20,000, fostering meaningful impact and contributions to the ecosystem.
          <br>• Documented and analyzed community feedback to identify areas for improvement and support community members with onboarding and education.
      - layout: right
        title: PwC Australia
        sub_title: Technology Risk / Cyber Security Project Coordinator
        caption: Sydney, AU | Jan 2019 - Aug 2021
        link: pwc.com.au
        quote: >
          Audit and Assurance, Consulting Firm
        description: | # this will include new lines to allow paragraphs
          <br>• Successfully coordinated and managed technology risk and cyber security projects for Commonwealth Bank with over $20m  budget ensuring compliance with standards and regulations.
          <br>• Collaborated closely with cross-functional teams to identify and mitigate potential security risks, implementing effective risk management strategies for
          <br>• Conducted regular risk assessments and monitored security systems to identify and address vulnerabilities for NSW Electoral Commission iVote Audit Reporting with $10.5m budget.
          <br>• Developed and maintained project plans, timelines, and budgets for technology risk and cyber security initiatives.
          <br>• Built and nurtured relationships with stakeholders, including key partners and vendors, to drive project success and ensure alignment on goals and priorities.
          <br>• Acted as a liaison between the security team and other departments, ensuring clear communication and alignment on security protocols and procedures.
          <br>• Led regular training and education sessions for employees to promote security awareness and best practices.
          <br>• Documented and analyzed security incidents to identify areas for improvement and support incident response efforts.
          <br>• Monitored and reported on compliance with industry standards and regulations, and implemented necessary changes to maintain compliance.

      - layout: right
        border: weak
        sub_title: Technology Risk/Cyber Security Consultant
        caption: Sydney, AU | Jun 2017 - Aug 2021
        description: |
          <br>• Facilitating client meetings to gather business requirements, while translating and simplifying requirements.
          <br>• Working with business users/stakeholders to assist with the business case, document business requirements for developing reports/processes.
          <br>• Analyzed data using SQL and Python to identify trends and patterns
          <br>• Created visualizations using Tableau to communicate findings to stakeholders
          <br>• Collaborated with technical and non-technical team members to define project requirements and develop technical solutions
          <br>• Troubleshoot and resolved issues that arose during the course of a project
          <br>• Identifying and evaluating inefficiencies and recommending optimal business practices, and system functionality and behavior.
          <br>• Using data and process modeling techniques to create clear system specifications for the design and development of system software.
          <br>• Preparation of technical reports and presentations.
          <br>• Using cyber security certifications and frameworks such as ISO 2700 and NIST to develop and enhance security policies, standards and processes inalignment with business strategy.
          <br>• Development and analysis of the cyber risk strategy, framework and process related to information technology, operational technology and/orconsumer technology.
          <br>• IT Audit Support (ITGC) - Provide support for the examination of the management controls within an Information technology (IT) infrastructure.

      - layout: left
        title: Optus
        sub_title: Junior Project Manager 
        link: optus.com.au
        caption: Sydney, AU | Aug 2016 - Jun 2017
        quote: >
          Telecommunications Company
        description: |
          <br>• Assisted in defining and clarifying project scope and objectives, ensuring technical feasibility and alignment with company strategy
          <br>• Developed and maintained detailed project plans to track progress, including all tasks, milestones and deadlines
          <br>• Coordinated internal and external resources, including allocating tasks, managing and monitoring project progress, making adjustments as necessary to ensure successful completion
          <br>• Established and maintained relationships with project stakeholders, including clients, vendors and internal teams
          <br>• Communicated project status, issues, and successes to stakeholders, including project team, management, and clients
          <br>• Led the project's change control process and ensured all changes are tracked, analyzed, and approved.
          <br>• Proactively identified and managed project risks and issues, and developed action plans to mitigate and resolve them
          <br>• Assisted in the development of project budgets and financial forecasting
      - layout: left
        border: weak
        sub_title: Technical Support Analyst 
        caption: Sydney, AU | Feb 2016 - Aug 2016
        description: |
          <br>• Documenting and tracking all received incidents in incident management system
          <br>• Collecting and updating data to assist with customer issues and concerns
          <br>• Assisted the manager with software installations
          <br>• Providing inter-departmental collaboration by escalating unresolved issues to appropriate support functions.
          <br>• Identifying priority calls and highlighting potential problems, ensuring that targets are met in line with tight key performance indicators.
          <br>• Using ServiceNow, NMC tools, IFMS, Helix, Boris, Map Blaster, GSMIS call tracking systems to log, track and manage Incidents.
          <br>• Enhanced communication skills by liaising with colleagues and different levels of management.
          <br>• Worked at the incident management team of 25 by displaying collaboration and support
          <br>• Training new employees on operational matters and company culture
      - layout: right
        title: Ample IT Solutions
        sub_title: Project Manager
        caption: Sydney, AU | Dec 2014 - Jun 2016
        link: ampleitsolutions.com.au
        quote: >
          IT Consulting
        description: | # this will include new lines to allow paragraphs
          <br>• Project planning: Developing detailed project plans and schedules, including scope, budget, resources, and timeline
          <br>• Risk management: Identifying and managing risks and issues that may impact the project
          <br>• Stakeholder communication: Communicating project progress and issues to stakeholders, including team members, clients, and senior management
          <br>• Resource management: Allocating and managing resources, including people and budgets, to ensure the project stays on track
          <br>• Quality assurance: Ensuring that the project is delivered to the required quality standards and meets business objectives
          <br>• Team leadership: Leading and motivating project teams to deliver high-quality results
          <br>• Budget management: Managing project budgets and financial resources effectively

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Western Sydney University
        sub_title: Master of Information and Communications Technology (MICT)
        caption: 2014 - 2016
#        quote: >
#          Short institution or course description (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of qualification
      - layout: top-middle
        title: Middlesex University London
        sub_title: Bachelor of Science (BSc) Information Technology
        caption: 2009 - 2013
#        quote: >
#          Short institution or course description (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of qualification
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      With a strong background in Scrum/Kanban and Agile Development, I am experienced in managing and leading projects through the entire software development life cycle (SDLC). I excel in creating process flows and modeling to streamline operations and improve efficiency. My analytical skills in data analysis and cost-benefit analysis, coupled with my ability in strategic planning, allow me to make informed decisions that drive project success. I am proficient in tools such as Confluence, RPA, Tableau, and SQL, which I use to collect and analyze data, and make data-driven decisions.

      I am a skilled communicator and have a talent for building relationships, this has allowed me to work effectively with team members, stakeholders and clients. I am proactive in my approach to work and have a great sense of time management. I am also well-versed in Jira, and use it to manage tasks and track progress. I am confident in my ability to lead projects from concept to launch and exceed success goals, and I am always looking for opportunities to improve and grow my skills.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Since 2021, I've been roaming between Europe, Asia, and Australia, using to the fullest ability to work remotely. When I'm not working, I love to take time for myself by practising meditation, yoga and reading books. I am also a big foodie, always on the lookout for new and exciting culinary experiences. Whether it's trying a new recipe, or discovering a hidden gem of a restaurant, food is always on my mind. I believe that a healthy balance of work and play is essential for a fulfilling life, and I strive to incorporate this into my daily routine.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
